spring:
  main:
    banner-mode: off
  jackson:
    timeZone: Europe/Amsterdam
    locale: nl-NL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  file.name: ${catalina.base:target}/logs/schoolagenda.log
  level:
    opwvhk: trace
    org.springframework: info
