package opwvhk.planner;

public enum StaticPage {
	EMERGENCY_PLAN, SCHEDULE_AND_VACATIONS, SURVIVE_FRESHMAN_YEAR, PLANNING_HAND, SURVIVE_LEARNING, USEFUL_STUFF,
	STUDYING_TIPS, HOW_TO_LEARN, PREREQUISITES_LEARNING, PLANNING_INSTRUCTIONS, PERSONAL_GOALS, GRADE_LIST
}
